### ISSUE TITLE
Rim width do not work with kotlin (error parse typed array)

### ISSUE THREAD

**Issue by AlexeyBoldakov** [Kaishu-Sahu/N-SidedProgressBar#2]
Hi, error parse array because, attr is float, but type array get int

**Comment by Kaishu-Sahu** [comment]
I have fixed the error. You can get the updated code by
`implementation 'com.kaishu.nspb:nsidedprogressbar:1.0.2'`
Let me know if the problem still exists.

**Comment by AlexeyBoldakov** [comment]
Hello, Thanks a lot!  Bug is fixed

As a request, could you add the ability to change corner radius? I tried adding the CornerPathEffect, but it didn't work for me.
